global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - flink.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: kafka
    static_configs:
      - targets: [ 'jmxexporter:5556' ]
  - job_name: 'flink'
    static_configs:
      - targets: [ 'jobmanager:9249', 'taskmanager:9249' ]

#global:
#  scrape_interval: 5s
#  evaluation_interval: 5s
#scrape_configs:
#  - job_name: "prometheus"
#    static_configs:
#      - targets: ["localhost:9090"]
##  - job_name: "otel-collector"
##    static_configs:
##      - targets: ["otel-collector:9292"]